# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 380bd72d0ca9ad4dc3e18766eece1112774c0d5f9e6a9e7ff009dd5db0dda940097cf120acd7f263fa130bf389e0b54fe21fe156f13b3098a2d334518fdc1c3a

test:
  secret_key_base: 2b19ddbcfe4b744b19eaa367ab8f866e19d3b284137fa80ee0c6f9106620ccc51fc7c362f3a3dcee6ec274b5e6aabe89f791f2d3423253df473a79b2becb8bf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
